### ISSUE TITLE
Fully namespace `Result`

### ISSUE THREAD

**Issue by adwhit** [quodlibetor/diesel-derive-newtype#5]
Hi, thanks for the useful lib.

Hit a confusing error when deriving a newtype within a module which clobbers the `Result` type. This is a pretty common idiom AFAICT.
```rust
type Result<T> = std::result::Result<T, MyError>;

#[derive(DieselNewType)]
pub struct Id(i32);
```
Gives the unhelpful error:
```
error[E0244]: wrong number of type arguments: expected 1, found 2
  --> src/lib.rs:16:10
   |
16 | #[derive(DieselNewType)]
   |          ^^^^^^^^^^^^^ expected 1 type argument
```
A fix would be to fully-namespace the `Result` type whereever it is used.

**Comment by quodlibetor** [comment]
Ah, yeah that makes sense! I'll get a fix for that out hopefully tonight, but definitely by the weekend.

Alternatively, if you'd like to do a PR I will happily merge and publish.
